[build]
  base    = "frontend"
  publish = "frontend"
  ignore  = "exit 0"

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
